package io.github.bigswlittlesw.homelight.config;

import io.smallrye.config.ConfigMappingLoader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/// Spike build step for the `native` profile: writes SmallRye's `$$CMImpl` classes into the
/// main output directory. Native Image cannot define classes at runtime; SmallRye loads an
/// existing implementation class before generating one, so pre-generated bytes are used as-is.
public final class NativeConfigMappingGenerator {
    public static void main(String[] args) throws IOException {
        var outputRoot = Path.of(args[0]);
        for (var metadata : ConfigMappingLoader.getConfigMappingsMetadata(HomeLightMapping.class)) {
            var file = outputRoot.resolve(metadata.getClassName().replace('.', '/') + ".class");
            Files.createDirectories(file.getParent());
            Files.write(file, metadata.getClassBytes());
            System.out.println("Generated " + file);
        }
    }
}
