[versions]
picocli = "4.7.7"

[libraries]
tamboui-bom = { module = "dev.tamboui:tamboui-bom", version = "0.5.0-SNAPSHOT" }
tamboui-toolkit = { module = "dev.tamboui:tamboui-toolkit" }
tamboui-jline3-backend = { module = "dev.tamboui:tamboui-jline3-backend" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.4" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version = "2.18.3" }
junit-bom = { module = "org.junit:junit-bom", version = "5.12.0" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
graalvm-native = { id = "org.graalvm.buildtools.native", version = "1.1.8" }
