"""Actual existing views plus workspace, driven in sized PTYs; no filesystem fixtures."""
from pathlib import Path

exec(Path('docs/research/session-c-prototype/terminal-walkthrough.py').read_text().split('for width, height in [(80, 24)')[0])

for width, height in [(80, 24), (120, 30)]:
    t = PrototypeTerminal(width, height)
    t.snap('A actual Status view')
    t.key('2l'); t.snap('A actual Plan choices')
    t.key('i'); t.snap('full details escape hatch'); t.key('n')
    t.key('v'); t.snap('B workspace same relocation')
    t.key('l'); t.snap('B first choice')
    for n in range(3):
        t.key('j'); t.snap('B choice ' + str(n + 2))
    t.resize(120 if width == 80 else 80, 30 if height == 24 else 24)
    t.pump(.4); t.snap('resize selected fourth choice')
    t.resize(width, height); t.pump(.4)
    t.key('kkk '); t.snap('B draft selected')
    t.key('3'); t.snap('same existing Apply review')
    t.key('n'); t.snap('B cancel retains focus')
    t.key('v'); t.snap('A Status saved policy same session')
    t.key('2'); t.snap('A Plan retains same draft')
    t.key('v3y'); t.pump(2); t.key('k', .1); t.snap('manual action inspection')
    t.pump(2); t.snap('follow next action')
    t.pump(18); t.snap('successful result')
    t.key('1'); t.snap('workspace updated observations')
    t.key('3'); t.snap('retained result')
    t.key('r3'); t.snap('no change review')
    t.key('n!2'); t.key('l 3y'); t.snap('preflight rejected')
    t.key('i'); t.snap('preflight explicit zero changes'); t.key('n')
    t.key('r'); t.snap('recovery replan')
    t.key('!3l 3y'); t.pump(6); t.snap('partial failure existing Apply view')
    t.key('i'); t.snap('partial explicit counts'); t.key(']'); t.snap('partial full messages'); t.key('n')
    t.key('!44u '); t.snap('missing default manual candidate selected')
    t.key('f'); t.snap('refresh retains candidate'); t.key('n'); t.snap('cancel no save')
    t.key('4 s'); t.snap('explicit save review'); t.key('y'); t.snap('saved entries feed actual planner')
    t.key('4f'); t.snap('refresh preserves configured entries'); t.key('n')
    t.key('!54'); t.snap('missing explicit setup'); t.key('n')
    t.quit()
